# Generated by Django 4.2.4 on 2023-09-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Petrol Price')),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diesel Price')),
                ('extrapremium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Extra Premium Price')),
                ('extragreen', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Extra Green Price')),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
