# Generated by Django 4.2.4 on 2023-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
