# Generated by Django 4.2.4 on 2023-09-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_time', models.TimeField(null=True)),
            ],
        ),
    ]
