# Generated by Django 4.2.4 on 2023-12-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_credittransaction_modeofpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='modeOfPayment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
