# Generated by Django 4.2.4 on 2023-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_credittransaction_modeofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='markAsPasid',
            field=models.BooleanField(default=True),
        ),
    ]
