# Generated by Django 4.2.4 on 2023-12-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_credittransaction_markaspasid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittransaction',
            old_name='markAsPasid',
            new_name='markAsPaid',
        ),
    ]
