# Generated by Django 4.2.4 on 2023-09-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_reading_openstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='card',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='cash',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='paytm',
            field=models.IntegerField(null=True),
        ),
    ]
