# Generated by Django 4.2.4 on 2023-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_reading_card_reading_cash_reading_paytm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='opening',
        ),
        migrations.AddField(
            model_name='reading',
            name='opening1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='nossle',
            field=models.IntegerField(null=True),
        ),
    ]
