# Generated by Django 4.2.4 on 2023-09-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_remove_reading_opening_reading_opening1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='opening1',
            new_name='openingP',
        ),
    ]
