# Generated by Django 4.2.4 on 2023-09-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_rename_opening1_reading_openingp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='closing',
            new_name='closingD',
        ),
        migrations.AddField(
            model_name='reading',
            name='closingP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='dispensingUnit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='openingD',
            field=models.IntegerField(null=True),
        ),
    ]
