# Generated by Django 4.2.4 on 2023-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_rename_closing_reading_closingd_reading_closingp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='expected',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='received',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='shortage',
            field=models.IntegerField(null=True),
        ),
    ]
