# Generated by Django 4.2.4 on 2023-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_reading_expected_reading_received_reading_shortage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
