# Generated by Django 4.2.4 on 2023-09-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0008_reading_date_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
