# Generated by Django 4.2.4 on 2023-09-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_reading_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='openstatus',
        ),
    ]
