# Generated by Django 4.2.4 on 2023-10-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_remove_reading_openstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='oil',
            field=models.IntegerField(null=True),
        ),
    ]
