# Generated by Django 4.2.4 on 2023-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_reading_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='card',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='cash',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='closingD',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='closingP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='expected',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='oil',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='openingD',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='openingP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='paytm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='received',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='shortage',
            field=models.FloatField(null=True),
        ),
    ]
