# Generated by Django 4.2.4 on 2024-08-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0013_rename_closingd_reading_closingnozzle1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='nossle3and4',
        ),
    ]
