# Generated by Django 4.2.4 on 2023-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Du1Nozzle1', models.FloatField(null=True)),
                ('Du1Nozzle2', models.FloatField(null=True)),
                ('Du1Nozzle3', models.FloatField(null=True)),
                ('Du1Nozzle4', models.FloatField(null=True)),
                ('Du2Nozzle1', models.FloatField(null=True)),
                ('Du2Nozzle2', models.FloatField(null=True)),
                ('Du2Nozzle3', models.FloatField(null=True)),
                ('Du2Nozzle4', models.FloatField(null=True)),
                ('Du3Nozzle1', models.FloatField(null=True)),
                ('Du3Nozzle2', models.FloatField(null=True)),
                ('Du3Nozzle3', models.FloatField(null=True)),
                ('Du3Nozzle4', models.FloatField(null=True)),
                ('Du4Nozzle1', models.FloatField(null=True)),
                ('Du4Nozzle2', models.FloatField(null=True)),
                ('Du4Nozzle3', models.FloatField(null=True)),
                ('Du4Nozzle4', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'ClosingSales',
                'verbose_name_plural': 'ClosingSaless',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelSales', models.FloatField(null=True)),
                ('Debit', models.FloatField(null=True)),
                ('Oil', models.FloatField(null=True)),
                ('itemSales', models.FloatField(null=True)),
                ('openingBalance', models.FloatField(null=True)),
                ('totalCash', models.FloatField(null=True)),
                ('totalCard', models.FloatField(null=True)),
                ('totalpaytm', models.FloatField(null=True)),
                ('credit', models.FloatField(null=True)),
                ('closingBalance', models.FloatField(null=True)),
                ('shortage', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Saless',
            },
        ),
    ]
