# Generated by Django 4.2.4 on 2023-12-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='Debit',
            new_name='debit',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Oil',
            new_name='oil',
        ),
    ]
