# Generated by Django 4.2.4 on 2023-12-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_debit_sales_debit_rename_oil_sales_oil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='totalpaytm',
            new_name='totalPaytm',
        ),
    ]
