# Generated by Django 4.2.4 on 2024-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_totalpaytm_sales_totalpaytm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
