# Generated by Django 4.2.4 on 2025-01-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='dieselSales',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='extraGreenSales',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='extraPremiumSales',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='petrolSales',
            field=models.FloatField(null=True),
        ),
    ]
